### ISSUE TITLE
Github has no PM and I don't think I know your email

### ISSUE THREAD

**Issue by Bekwnn** [n00b0001/CSC473-ClothCollisions#1]
Hey, just opening this to let you know I'm going to head into uvic today (10th) to work on the project. If you can come that would be great, if not we really need to start setting up more dates when we can work on this thing.

**Comment by Bekwnn** [comment]
Also my email is e.w.nickerson@gmail.com

**Comment by n00b0001** [comment]
Yea, I was taking the weekend off to do groceries / chores / laundry / etc. I will be coming in every day from now on. See you there.

**Comment by Bekwnn** [comment]
That was Monday, and I actually wasn't planning to head in today given I still didn't get into contact with you. I'm heading in now, but I have to leave by 5:15ish and I might be about 30 mins until I get there.
- written at 2:31
